enable_sort_by_created_date_nav_bar_item:
  default: true
  type: bool
  description:
    en: Add a "Sort by Created Date" nav bar item.

enable_column_on_created_date_filter_only:
  default: false
  type: bool
  description:
    en: Add the "Created" column only when the "Sort by Created Date" nav bar item is selected.

enable_nav_bar_item_in_home_page:
  default: true
  type: bool
  description:
    en: Add the "Sort by Created Date" nav bar item in the home page.

enable_column_in_home_page:
  default: true
  type: bool
  description:
    en: Add the "Created" column in the home page.

categories_to_display_nav_bar_item:
  default: ""
  type: list
  list_type: category
  description:
    en: List of categories to display in the "Sort by Created Date" nav bar item. Leave empty to display in all categories.

categories_to_display_created_column:
  default: ""
  type: list
  list_type: category
  description:
    en: List of categories to display the "Created" column. Leave empty to display in all categories.
